<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProviderTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run()
    {
        $providers = [
            [
                'id' => 1,
                'first_name' => 'Mckeen',
                'middle_name' => 'Mamonong',
                'last_name' => 'Asma',
                'status' => '1',
                'pay_status' => 'Is Paying',
                'provider_type' => 'Specialist',
                'language' => 'English',
                'email' => 'mcasmakeen@gmail.com',
                'phone' => '9323900204',
                'provider_communication_note' => 'English',
                'headshot' => null,
                'lien' => null,
                'cv' => null,
                'signed_contract' => null,
                'w_9' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 2,
                'first_name' => 'Travis',
                'middle_name' => 'D',
                'last_name' => 'Chapman',
                'status' => '1',
                'pay_status' => 'Is Paying',
                'provider_type' => 'Therapist',
                'language' => 'English',
                'email' => 'provider@example.com',
                'phone' => '1231123141414',
                'provider_communication_note' => 'test',
                'headshot' => null,
                'lien' => null,
                'cv' => null,
                'signed_contract' => null,
                'w_9' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 3,
                'first_name' => 'Emily',
                'middle_name' => 'C',
                'last_name' => 'Johnson',
                'status' => '1',
                'pay_status' => 'Is Paying',
                'provider_type' => 'Specialist',
                'language' => 'English',
                'email' => 'emily.johnson@example.com',
                'phone' => '5555555557',
                'provider_communication_note' => 'Available in the morning',
                'headshot' => null,
                'lien' => null,
                'cv' => null,
                'signed_contract' => null,
                'w_9' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 4,
                'first_name' => 'Michael',
                'middle_name' => 'D',
                'last_name' => 'Williams',
                'status' => '1',
                'pay_status' => 'Is Paying',
                'provider_type' => 'Therapist',
                'language' => 'French',
                'email' => 'michael.williams@example.com',
                'phone' => '5555555558',
                'provider_communication_note' => 'French speaker',
                'headshot' => null,
                'lien' => null,
                'cv' => null,
                'signed_contract' => null,
                'w_9' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 5,
                'first_name' => 'Sarah',
                'middle_name' => 'E',
                'last_name' => 'Brown',
                'status' => '1',
                'pay_status' => 'Is Paying',
                'provider_type' => 'Specialist',
                'language' => 'English',
                'email' => 'sarah.brown@example.com',
                'phone' => '5555555559',
                'provider_communication_note' => 'Prefers email communication',
                'headshot' => null,
                'lien' => null,
                'cv' => null,
                'signed_contract' => null,
                'w_9' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 6,
                'first_name' => 'David',
                'middle_name' => 'F',
                'last_name' => 'Jones',
                'status' => '1',
                'pay_status' => 'Is Paying',
                'provider_type' => 'Therapist',
                'language' => 'Spanish',
                'email' => 'david.jones@example.com',
                'phone' => '5555555560',
                'provider_communication_note' => 'Spanish speaker',
                'headshot' => null,
                'lien' => null,
                'cv' => null,
                'signed_contract' => null,
                'w_9' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 7,
                'first_name' => 'Sophia',
                'middle_name' => 'G',
                'last_name' => 'Garcia',
                'status' => '1',
                'pay_status' => 'Is Paying',
                'provider_type' => 'Specialist',
                'language' => 'English',
                'email' => 'sophia.garcia@example.com',
                'phone' => '5555555561',
                'provider_communication_note' => 'Available in the afternoon',
                'headshot' => null,
                'lien' => null,
                'cv' => null,
                'signed_contract' => null,
                'w_9' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 8,
                'first_name' => 'James',
                'middle_name' => 'H',
                'last_name' => 'Miller',
                'status' => '1',
                'pay_status' => 'Is Paying',
                'provider_type' => 'Therapist',
                'language' => 'English',
                'email' => 'james.miller@example.com',
                'phone' => '5555555562',
                'provider_communication_note' => 'Test note',
                'headshot' => null,
                'lien' => null,
                'cv' => null,
                'signed_contract' => null,
                'w_9' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 9,
                'first_name' => 'Isabella',
                'middle_name' => 'I',
                'last_name' => 'Davis',
                'status' => '1',
                'pay_status' => 'Is Paying',
                'provider_type' => 'Specialist',
                'language' => 'Spanish',
                'email' => 'isabella.davis@example.com',
                'phone' => '5555555563',
                'provider_communication_note' => 'Spanish speaker',
                'headshot' => null,
                'lien' => null,
                'cv' => null,
                'signed_contract' => null,
                'w_9' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 10,
                'first_name' => 'William',
                'middle_name' => 'J',
                'last_name' => 'Martinez',
                'status' => '1',
                'pay_status' => 'Is Paying',
                'provider_type' => 'Therapist',
                'language' => 'English',
                'email' => 'william.martinez@example.com',
                'phone' => '5555555564',
                'provider_communication_note' => 'Prefers phone communication',
                'headshot' => null,
                'lien' => null,
                'cv' => null,
                'signed_contract' => null,
                'w_9' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        DB::table('providers')->insert($providers);
    }
}
