name: Deploy to Cloudways

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.CLOUDWAYS_SSH_KEY }}
          known_hosts: ${{ secrets.KNOWN_HOSTS }}

      - name: Deploy via SSH
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.CLOUDWAYS_USERNAME }}@${{ secrets.CLOUDWAYS_SERVER_IP }} << EOF
            cd ./applications/sagwcwkfme/public_html/
            php artisan down || true
            git fetch origin main
            git reset --hard origin/main
            php artisan migrate:new
            export NODE_OPTIONS=--max-old-space-size=8192
            npm install
            npm run build
            php artisan optimize:clear
            php artisan config:cache
            php artisan route:cache
            php artisan view:cache
            php artisan up
          EOF